

#' Get Roboflow masks/annotations as sf polygons and SpatRaster objects
#'
#' Extracts polygon masks from a JSON file, as formatted by Roboflow, and converts
#' them to `sf` polygon objects. Additionally, it creates raster masks from these
#' polygons based on specified image dimensions. This function is useful for
#' processing polygon annotations from machine learning datasets, particularly for
#' tasks involving spatial analysis or computer vision. It supports rescaling of
#' geometric data to match different image resolutions.
#'
#' @param path The file path to the JSON file containing polygon data.
#' @param rst_height The original height (number of rows) of the image used for annotation in Roboflow.
#'                   The same for height will be set in the output raster mask.
#'                   Defaults to 1440.
#' @param rst_width The width (number of columns) for the input image and output mask.
#'                  Defaults to 1080.
#' @param geom_rescale A numeric value or NULL. If specified, it is used to rescale
#'                     the polygon vertices to match a different image resolution.
#'                     This is useful when the annotation coordinates in the JSON
#'                     file are based on a different resolution than the target
#'                     raster. If NULL, no rescaling is applied.
#'
#' @return A list containing three elements: `labs` with the labels of the polygons,
#'         `pol_masks` with the `sf` polygon objects, and `rst_masks` with the
#'         corresponding raster masks.
#'
#' @importFrom jsonlite fromJSON
#' @importFrom sf st_linestring st_polygon st_sfc st_sf
#' @importFrom terra rast rasterize flip as.polygons
#' @importFrom magrittr %>%
#'
#' @export
#'

get_roboflow_masks <- function(path, rst_height = 1440, rst_width = 1080,
                               geom_rescale=NULL) {

  # JSON data loaded from a Roboflow json file
  json <- jsonlite::fromJSON(path)

  # Get object/masks labels
  labs <- json$boxes$label

  # Initiate the output object
  masks <- list(labs = c(),
                pol_masks = list(),
                rst_masks = list())

  # Create raster template to be used for rasterize function
  rr <- terra::rast(nrows = rst_height, ncols = rst_width, res = 1, crs = "",
             xmin = 0, ymin = 0, xmax = rst_width, ymax = rst_height)


  for(i in 1:length(labs)){

    # Get the label name
    label <- json$boxes$label[[i]]

    # Extract the vertices from the JSON object
    points <- json$boxes[,"points"][[i]]

    # Close the line to make a polygon
    points <- rbind(points, points[1,])


    if(!is.null(geom_rescale)){
      # Re-scale the points so that they fit the
      # low-resolution thermal image
      points <- points / geom_rescale
    }

    # Create an sf LINESTRING geometry from the points matrix
    linestring <- sf::st_linestring(points, dim = "XY")

    # Create an sf polygon from the LINESTRING
    polygon <- sf::st_polygon(list(linestring))
    sf_polygon <- sf::st_sfc(polygon)

    # Create an sf data frame with the polygon
    sf_polygon <- sf::st_sf(geometry = sf_polygon)

    # Create a raster mask based on the downscaled polygon
    mask <- terra::rasterize(sf_polygon, rr, value=1) %>%
      terra::flip(direction="v")

    # Save data into a dense list
    masks$labs[i] <- label
    masks$pol_masks[[i]] <- terra::as.polygons(mask)
    masks$rst_masks[[i]] <- mask
  }

  return(masks)
}

#' Simplify and aggregate masks by label from Roboflow annotations
#'
#' Aggregates polygon and raster masks by their labels from a list of masks,
#' produced by `get_roboflow_masks` function converting JSON polygon annotations to spatial formats.
#' This functioncombines polygons and raster masks of the same label into single, aggregated masks,
#' which is particularly useful for analyses that require handling each label as a single
#' entity or layer. The aggregation of raster masks involves creating a unified mask where
#' any pixel covered by at least one mask of a given label is marked as part of that label.
#'
#' @param masks A list generated by `get_roboflow_masks` containing the labels (`labs`),
#'              polygon masks (`pol_masks`), and raster masks (`rst_masks`) extracted from JSON
#'              annotations.
#'
#' @return A list similar in structure to the input but with all masks of the same label
#'         aggregated together. Each label will correspond to a single polygon mask and a
#'         single raster mask, with the latter indicating presence (1 or TRUE) or absence
#'         (NA) of the label at each pixel.
#'
#' @export

simplify_roboflow_masks <- function(masks){

  # Simplified masks output holding the masks
  # but with polygons of the same class joined together
  # as well as the rasters
  new_masks <- list(
    labs = c(),
    pol_masks = list(),
    rst_masks = list()
  )

  # List of unique labels used in Roboflow annotations
  ulabs <- unique(masks$labs)

  # Loop through labels
  for(k in 1:length(ulabs)){
    sel_lab <-  ulabs[k]
    lidxs <- (1:length(masks$labs))[masks$labs == sel_lab]


    if(length(lidxs) > 1){

      rst_list <- masks$rst_masks[lidxs]
      pol_list <- masks$pol_masks[lidxs]

      for(jj in 1:length(rst_list)){

        tr <- rst_list[[jj]]
        tr[is.na(tr)] <- 0

        pol <- pol_list[[jj]]

        if(jj==1){
          agg_rst <-  tr
          agg_pol <- pol
        }else{
          # Aggregate raster data
          agg_rst <- agg_rst + tr
          # Aggregate polygon data
          agg_pol <- rbind(agg_pol, pol)
        }
      }

      agg_rst <- agg_rst > 0
      agg_rst[agg_rst <= 0] <- NA

      new_masks[["labs"]][k] <- sel_lab
      new_masks[["pol_masks"]][[k]] <- agg_pol
      new_masks[["rst_masks"]][[k]] <- agg_rst

    }else{

      new_masks[["labs"]][k] <- sel_lab
      new_masks[["pol_masks"]][[k]] <- unlist(masks[["pol_masks"]][[lidxs]])
      new_masks[["rst_masks"]][[k]] <- unlist(masks[["rst_masks"]][[lidxs]])
    }
  }

  return(new_masks)
}
